
- name: master-0
  hosts: masters[0]
  become: true
  vars_files:
       - common_vars.yml

  tasks:
    - name: install rke2 in master-0
      ansible.builtin.import_tasks: ./masters/master-0.yml

    - name: install rke2 in masters
      ansible.builtin.import_tasks: ./masters/masters.yml
      
    - name: install rke2 in workers
      ansible.builtin.import_tasks: ./workers/workers.yml