apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: svccluster-west
spec:
  cidr: 10.1.0.0/16
  natOutgoing: false
  disabled: true

---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: podcluster-west
spec:
  cidr: 10.0.0.0/16
  natOutgoing: false
  disabled: true
