apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: open5gs
    meta.helm.sh/release-namespace: open5gs
  labels:
    app.kubernetes.io/instance: open5gs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: upf
  name: open5gs-upf-gtpu
  namespace: open5gs
spec:
  ports:
  - name: gtpu
    nodePort: 2152 
    port: 2152
    protocol: UDP
    targetPort: gtpu
  selector:
    app.kubernetes.io/instance: open5gs
    app.kubernetes.io/name: upf
  type: NodePort