apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: open5gs
    meta.helm.sh/release-namespace: open5gs
  labels:
    app.kubernetes.io/instance: open5gs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webui
  name: open5gs-webui
  namespace: open5gs
spec:
  ports:
  - name: http
    nodePort: 20000
    port: 9999
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: open5gs
    app.kubernetes.io/name: webui
  sessionAffinity: None
  type: NodePort