apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-api-region
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-api-region
  template:
    metadata:
      labels:
        app: mock-api-region
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-2-4-237.eu-west-3.compute.internal 
      imagePullSecrets:
        - name: harbor-secret        
      containers:
      - name: mock-api-region
        image: dockerhub.mobilesandbox.cloud:9443/tactile5g/wvl-speed-test-mock-api-region:latest
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: mock-api-region
spec:
  selector:
    app: mock-api-region
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
