apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-4-250.eu-west-3.compute.internal
      imagePullSecrets:
        - name: harbor-secret        
      containers:
      - name: web-ui
        image: dockerhub.mobilesandbox.cloud:9443/tactile5g/wvl-speed-test-web-ui:latest
        ports:
        - containerPort: 8501

---

apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  selector:
    app: web-ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort
