
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.4
    chart: external-secrets
    directory:
      recurse: false
  sources: []
  project: clusters
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true