apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: USER
    remoteRef:
      key: /oneke/user 
  - secretKey: PASSWORD
    remoteRef:
      key: /oneke/pwd
