apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-sm  # name of the externalsecret
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: secretstore-sample-sm  # name of the secretStore
    kind: SecretStore
  target:
    name: secret-to-be-created-sm # name use for the pod to take the secrets
    creationPolicy: Owner
  data:
  - secretKey: USER   # variable where the secret will be store and used for the pod
    remoteRef:
      key: oneke/credentials # name of the parameter secret aws
      property: USER
#  - secretKey: PASSWORD
#    remoteRef:
#      key: oneke/creds
#      property: PASSWORD
