apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-sm
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: secretstore-sample-sm
    kind: SecretStore
  target:
    name: secret-to-be-created-sm
    creationPolicy: Owner
  data:
  - secretKey: USER
    remoteRef:
      key: oneke/creds
      property: USER
  - secretKey: PASSWORD
    remoteRef:
      key: oneke/creds
      property: PASSWORD
