apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-pm   # name of the externalsecret
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: secretstore-sample-pm    # name of the secretStore
    kind: SecretStore
  target:
    name: secret-to-be-created-pm   # name use for the pod to take the secrets
    creationPolicy: Owner
  data:
  - secretKey: USER  # variable where the secret will be store and used for the pod
    remoteRef:
      key: /oneke/user  # name of the parameter secret aws
  - secretKey: PASSWORD  # variable where the secret will be store and used for the pod
    remoteRef:
      key: /oneke/pwd  # name of the parameter secret aws
