apiVersion: v1
kind: Pod
metadata:
    name: secret-pod
    labels:
        name: secret-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 5000;done"]
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: secret-to-be-created-pm
        - secretRef:
            name: secret-to-be-created-sm
