apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample-pm
spec:
  provider:
    aws:
      service: ParameterStore 
      region: eu-west-3
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret  # secret created with the user aws credentials
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret   # secret created with the user aws credentials
            key: secret-access-key
