apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trivy-operator

helmGlobals:
  chartHome: trivy-operator
helmCharts:
  - name: trivy-operator
    includeCRDs: true
    releaseName: trivy-operator
    version: 0.10.1
