---
# tasks file for ansible-rk2

- name: stop firewall
  ansible.builtin.systemd:
    state: stopped
    name: ufw
  ignore_errors: true

- name: install nfs-common package
  ansible.builtin.apt:
    name: nfs-common
    state: latest

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: create rke2 directory
  ansible.builtin.file:
    path: /etc/rancher/rke2/
    state: directory
    recurse: true
    mode: '0755'

- name: get hostname
  ansible.builtin.setup:
    filter: ansible_hostname
  register: result

- name: adding content config.yaml
  ansible.builtin.blockinfile:
    path: /etc/rancher/rke2/config.yaml
    create: true
    block: |
      disable:
        - rke2-ingress-nginx
      cloud-provider-name: aws
      token: my-shared-secret
      tls-san:
        - {{ nlb }}
        - {{ result.ansible_facts.ansible_hostname }}

- name: download RKE2 install script
  get_url:
    url: https://get.rke2.io
    dest: /usr/local/bin/install-rke2.sh
    mode: 0755
    
- name: install rke2 master
  ansible.builtin.shell: |
     bash /usr/local/bin/install-rke2.sh

- name: enable and start rk2
  ansible.builtin.systemd:
    name: rke2-server.service
    enabled: true
    state: started

- name: find kubectl file
  ansible.builtin.find:
    paths: /var/lib/rancher/rke2/data/
    patterns: kubectl
    file_type: file
    recurse: yes
  register: kubectl_path

- name: create a symbolic link for kubectl
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    src: "{{ kubectl_path.files[0].path }}"
    state: link
    force: yes
