apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-pod
        imagePullPolicy: Always
        image: nginx:latest
        ports:
        - containerPort: 80 

---

apiVersion: v1
kind: Service
metadata:
  name: my-cilium-lb-service
spec:
  type: NodePort 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 36162
  selector:
    app: nginx-pod