apiVersion: v1
kind: Service
metadata:
  name: hubble-svc-ui
  namespace: kube-system
spec:
  type: NodePort 
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 35162
  selector:
    k8s-app: hubble-ui