apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.16.2
- condition: keycloak.install
  name: keycloak
  repository: https://codecentric.github.io/helm-charts
  version: 17.0.3
- condition: argo-cd.install
  name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: 5.6.0
- condition: sealed-secrets.install
  name: sealed-secrets
  repository: https://bitnami-labs.github.io/sealed-secrets
  version: 2.7.0
description: A Helm chart for Ahoy; release manager tool for Kubernetes
home: https://ahoyrm.io/
icon: https://ahoyrm.io/wp-content/uploads/2022/08/cropped-AHOY-Logos-Final-Transparent-03-192x192.png
keywords:
- ahoy
- ahoyrm
- releasemanager
- gitops
maintainers:
- name: lsdopen
  url: https://lsdopen.io/
name: ahoy
sources:
- https://github.com/lsdopen/ahoy-helm/tree/main/charts/ahoy
- https://github.com/lsdopen/ahoy
version: 1.0.0
