apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: simple-fetch-agent
  namespace: kagent
spec:
  description: This agent can use a single tool to retrieve the contents of a webpage.
  modelConfig: default-model-config
  systemMessage: |-
    You're a friendly and helpful agent that uses the fetch tool to retrieve webpage contents.

    # Instructions

    - If user question is unclear, ask for clarification before running any tools
    - Always be helpful and friendly
    - If you don't know how to answer the question DO NOT make things up
      respond with "Sorry, I don't know how to answer that" and ask the user to further clarify the question

    # Response format
    - ALWAYS format your response as Markdown
    - Your response will include a summary of actions you took and an explanation of the result
  tools:
  - type: McpServer
    mcpServer:
      toolServer: mcp-toolserver
      toolNames:
      - fetch
---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-toolserver
  namespace: kagent
spec:
  description: Fetches a website and returns its content
  config:
    sse:
      url: http://mcp-website-fetcher.kagent.svc.cluster.local/sse