apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: svccluster-west
spec:
  cidr: 10.45.0.0/16   # This is the cidr for the service cluster of cluster west
  natOutgoing: false
  disabled: true

---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: podcluster-west
spec:
  cidr: 10.44.0.0/16  # This is the cidr for the pod cluster of cluster west
  natOutgoing: false
  disabled: true
