apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: svccluster-east
spec:
  cidr: 10.99.0.0/16   # This is the cidr for the service cluster of cluster east
  natOutgoing: false
  disabled: true

---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: podcluster-east
spec:
  cidr: 10.98.0.0/16    # This is the cidr for the pod cluster of cluster east
  natOutgoing: false
  disabled: true
