apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-client
  template:
    metadata:
      labels:
        app: iperf3-client
    spec:
      containers:
      - name: iperf3-client
        image: networkstatic/iperf3
        command: ["/bin/sh", "-c"]
        args: ["sleep 3600"]
