apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# adding extra configuration in base/pod.yaml, base/deployment
patchesStrategicMerge:
- patch-pod.yaml
- env-dev.yaml

# overiding values, it will change the tag of the image in deployment, pods yamls
images:
- name: nginx
  newTag: 1.1.1