# create clusterissuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-tactile5g
spec:
  selfSigned: {}

---
# create self-signed certtificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certi-ca-tactile5g
  namespace: cert-manager
spec:
  isCA: true
  commonName: tactile5g
  secretName: tactile5g
  dnsNames:
   - "*.tactile5g.int"
  issuerRef:
    name: selfsigned-tactile5g
    kind: ClusterIssuer
    group: cert-manager.io

---

# create clusterissuer that use ca certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tactile5g-cissuer
spec:
  ca:
    secretName: tactile5g

