apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
 name: k8s-action-deployment-apps
 namespace: actions-runner-system
spec:
 replicas: 3
 template:
   spec:
     repository: andresanaya21/deployment-apps