services:
  # One-shot manual run: executes the bot once and exits
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: qmatic-bot-once
    environment:
      BASE_URL: "https://citaprevia.ciencia.gob.es/qmaticwebbooking/#/"
      TARGET_TRAMITE: "Asistencia telefónica para la homologación y equivalencia de títulos universitarios extranjeros"
      CONTACT_NAME: "Monica Pérez Villarroel"
      CONTACT_ID: "Z0428685Q"
      CONTACT_EMAIL: "monicaperezvillarroel060@gmail.com"
      CONTACT_PHONE: "613304514"
      HEADLESS: "true"
      SLOW_MO_MS: "0"
      MAX_MONTHS_TO_SCAN: "6"
      DEFAULT_TIMEOUT_MS: "25000"
      TZ: "Europe/Madrid"
    volumes:
      - ./bot/artifacts:/app/artifacts
      - ./bot/videos:/app/videos
    # Override image CMD to run the bot once
    command: ["python", "book_appointment_real.py"]

  # Always-on tick runner: triggers the bot every 5s in the allowed window
  ticker:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: qmatic-bot-ticker
    environment:
      BASE_URL: "https://citaprevia.ciencia.gob.es/qmaticwebbooking/#/"
      TARGET_TRAMITE: "Asistencia telefónica para la homologación y equivalencia de títulos universitarios extranjeros"
      CONTACT_NAME: "Monica Pérez Villarroel"
      CONTACT_ID: "Z0428685Q"
      CONTACT_EMAIL: "monicaperezvillarroel060@gmail.com"
      CONTACT_PHONE: "613304514"
      HEADLESS: "true"
      SLOW_MO_MS: "0"
      MAX_MONTHS_TO_SCAN: "6"
      DEFAULT_TIMEOUT_MS: "25000"
      TZ: "Europe/Madrid"
      # Optional: change tick interval (seconds)
      TICK_INTERVAL: "5"
    volumes:
      - ./bot/artifacts:/app/artifacts
      - ./bot/videos:/app/videos
    restart: unless-stopped