services:
  # One-shot manual run: executes the bot once and exits
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: qmatic-bot-once
    environment:
      BASE_URL: "https://citaprevia.ciencia.gob.es/qmaticwebbooking/#/"
      TARGET_TRAMITE: "Asistencia telefónica para la homologación y equivalencia de títulos universitarios extranjeros"
      # --- Contact fields (extended) ---
      CONTACT_NAME: "Monica"
      CONTACT_LASTNAME: "Pérez Villarroel"
      CONTACT_ID: "Z0428685Q"
      CONTACT_EMAIL: "monicaperezvillarroel060@gmail.com"
      CONTACT_EMAIL_CONFIRM: "monicaperezvillarroel060@gmail.com"
      CONTACT_PHONE_CC: "+34"
      CONTACT_PHONE: "613304514"
      CONTACT_PHONE_CONFIRM: "613304514"
      CONTACT_NOTES: "información de expediente 2022-06976"
      CONTACT_CONSENT: "true"   # must be "true" or "false"
      # --- Bot behavior ---
      HEADLESS: "true"
      SLOW_MO_MS: "0"
      MAX_MONTHS_TO_SCAN: "6"    # override default (2) if you really want to scan further
      DEFAULT_TIMEOUT_MS: "25000"
      TZ: "Europe/Madrid"
    volumes:
      - ./bot/artifacts:/app/artifacts
      - ./bot/videos:/app/videos
    # Run the bot once
    command: ["python", "book_appointment_real.py"]

  # Always-on tick runner: triggers the bot every 5s in the allowed window
  ticker:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: qmatic-bot-ticker
    environment:
      BASE_URL: "https://citaprevia.ciencia.gob.es/qmaticwebbooking/#/"
      TARGET_TRAMITE: "Asistencia telefónica para la homologación y equivalencia de títulos universitarios extranjeros"
      # Keep minimal env here; pass the detailed ones via BOT_EXTRA_ENV so the
      # tick runner forwards them to the spawned bot process as well.
      HEADLESS: "true"
      SLOW_MO_MS: "0"
      MAX_MONTHS_TO_SCAN: "6"
      DEFAULT_TIMEOUT_MS: "25000"
      TZ: "Europe/Madrid"
      TICK_INTERVAL: "5"
      BOT_TIMEOUT: "240"
      WINDOW_DAYS: "SUN,MON,TUE,WED"
      WINDOW_START: "12:10"
      WINDOW_END: "14:00"
      BOT_EXTRA_ENV: >
        HEADLESS=true,
        SLOW_MO_MS=0,
        DEFAULT_TIMEOUT_MS=30000,
        CONTACT_NAME=Monica,
        CONTACT_LASTNAME=Pérez Villarroel,
        CONTACT_ID=Z0428685Q,
        CONTACT_EMAIL=monicaperezvillarroel060@gmail.com,
        CONTACT_EMAIL_CONFIRM=monicaperezvillarroel060@gmail.com,
        CONTACT_PHONE_CC=+34,
        CONTACT_PHONE=613304514,
        CONTACT_PHONE_CONFIRM=613304514,
        CONTACT_NOTES=información de expediente 2022-06976,
        CONTACT_CONSENT=true
    volumes:
      - ./bot/artifacts:/app/artifacts
      - ./bot/videos:/app/videos
    restart: unless-stopped