---
# helm module not available using ansible 2.9. Ansible 8 version still not released

- name: aws load balanacer controller
  block:
    - name: Add helm repo
      command: helm repo add eks https://aws.github.io/eks-charts
      
    - name: Apply the configuration using kubectl
      k8s:
        state: present
        src: ./crds.yaml
        kubeconfig: "{{ path_kubeconfig }}"

    - name: Update helm repo
      command: helm repo update

    - name: Install aws load balanacer controller
      command: >
        helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system 
        --set clusterName=clusster-mgmt 
        --kubeconfig {{ path_kubeconfig }}
  when: "{{ aws_lb_controller.enable }} == true"
