---
# helm module not available using ansible 2.9. Ansible 8 version still not released

- name: ingress nginx
  block:
    - name: Add helm repo
      command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update helm repo
      command: helm repo update

    - name: Install ingress nginx
      command: >
        helm upgrade -i ingress-nginx ingress-nginx/ingress-nginx \
        --version 4.2.3 \
        --namespace kube-system \
        --set controller.service.type=ClusterIP
  when: "{{ ingress_nginx.enable }} == true"
