apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server-loxilb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server-loxilb
  template:
    metadata:
      labels:
        app: iperf3-server-loxilb
    spec:
      containers:
      - name: iperf3-server-loxilb
        image: networkstatic/iperf3
        args: ["-s"]
        ports:
        - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server-loxilb
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "fullnat"
    loxilb.io/staticIP: "10.95.82.149"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: iperf3-server-loxilb
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
  type: LoadBalancer