---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NS}
  annotations:
    metallb.universe.tf/address-pool: ip-pooladdress-local
  labels:
    app.kubernetes.io/name: ${SERVICE_NAME}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ${SERVICE_NAME}
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP