name: install dependencies
on: 
  push:
    branches:
      - main
jobs:   
  monitoring:
    name: dependencies
    runs-on: self-hosted
    steps:
    - name: Info runner
      run: |
       echo "### starting workflow ###"
       export TEST=$(hostname)
       echo "This test was executed in $TEST"
       
    - name: install dependencies
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash