name: securiry scanning to monitoring addons
on: 
  push:
    branches:
      - main
jobs:   
  monitoring:
    name: monitoring
    runs-on: self-hosted
    steps:
    - name: pulling repository
      uses: actions/checkout@v3
      with:
        repository: 'andresanaya21/andresanaya21'
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.ACCESS_TOKEN }}
 
    - name: Info runner
      run: |
       echo "### starting workflow ###"
       export TEST=$(hostname)
       echo "This test was executed in $TEST"

    - name: install dependencies
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: folder terrascan monitoring
      run: |
        mkdir monitoring/terrascan

    - name: k8s manifest monitoring/grafana
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm template grafana/grafana  > \
        monitoring/terrascan/manifest-grafana.yaml

    - name: k8s manifest monitoring/prometheus
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm template prometheus-community/kube-prometheus-stack > \
        monitoring/terrascan/manifest-prometheus.yaml

    - name: artifact manifiests monitoring
      uses: actions/upload-artifact@master
      with:
        name: manifests-monitoring
        path: monitoring/terrascan
        
  terrascan_monitoring:
    needs: monitoring
    runs-on: self-hosted
    name: terrascan-action
    steps:
    - name: artifact
      uses: actions/download-artifact@master
      with:
        name: manifests-monitoring
        path: monitoring/terrascan

    - name: Run Terrascan monitoring
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        policy_type: 'k8s'
        only_warn: true
        sarif_upload: true
        iac_dir: monitoring/terrascan
        #non_recursive:
        #policy_path:
        #skip_rules:
        #config_path:

    - name: Upload SARIF file monitoring
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: terrascan.sarif