name: securiry scanning
on: 
  push:
    branches:
      - main

jobs:
#  download_helm:
#    name: dowload helm chart
#    runs-on: self-hosted
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v3
#      with:
#        repository: 'andresanaya21/andresanaya21'
#        ref: ${{ github.head_ref }}
#        fetch-depth: 0
#        token: ${{ secrets.ACCESS_TOKEN }}
#
#    - name: Info runner
#      run: |
#       echo "### starting workflow ###"
#       export TEST=$(hostname)
#       echo "This test was executed in $TEST"
#
#    - name: install dependencies
#      run: |
#        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
#  
#    - name: k8s manifest security/cert-manager
#      run: |
#        mkdir cert-manager/terrascan
#        helm repo add jetstack https://charts.jetstack.io
#        helm template  jetstack/cert-manager --set installCRDs=true > \
#        cert-manager/terrascan/manifest.yaml

  terrascan_job:
    needs: download_helm
    runs-on: self-hosted
    name: terrascan-action
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 'andresanaya21/andresanaya21'
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.ACCESS_TOKEN }}
        
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        iac_version: 'v14'
        policy_type: 'k8s'
        only_warn: true
        sarif_upload: true
        iac_dir: cert-manager/terrascan
        #non_recursive:
        #policy_path:
        #skip_rules:
        #config_path:

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
