name: securiry scanning security addons
on: 
  push:
    branches:
      - main

jobs:
  security:
    name: security
    runs-on: self-hosted
    steps:
    - name: pulling repository
      uses: actions/checkout@v3
      with:
        repository: 'andresanaya21/andresanaya21'
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Info runner
      run: |
       echo "### starting workflow ###"
       export TEST=$(hostname)
       echo "This test was executed in $TEST"

    - name: install dependencies
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: folder terrascan security
      run: |
        mkdir -p security/terrascan

    - name: k8s manifest security/cert-manager
      run: |
        helm repo add jetstack https://charts.jetstack.io
        helm template  jetstack/cert-manager --set installCRDs=true > \
        security/terrascan/manifest-cert-manager.yaml

    - name: artifact manifiest security
      uses: actions/upload-artifact@master
      with:
        name: manifests-security
        path: security/terrascan/

  terrascan_security:
    needs: security
    runs-on: self-hosted
    name: terrascan-action
    steps:
    - name: artifact 
      uses: actions/download-artifact@master
      with:
        name: manifests-security
        path: security/terrascan/

    - name: Run Terrascan security
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        policy_type: 'k8s'
        only_warn: true
        sarif_upload: true
        iac_dir: security/terrascan
        #non_recursive:
        #policy_path:
        #skip_rules:
        #config_path:

    - name: Upload SARIF file security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: terrascan.sarif