apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-k8s-advanced
  namespace: vcluster
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-k8s-advanced
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-k8s-advanced
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: cluster-k8s-advanced
  namespace: vcluster
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: cluster-k8s-advanced
      repo: null
      version: null
    values: |-
      enableHA: true
      service:
        type: LoadBalancer
      sync:
        persistentvolumeclaims:
          enabled: true
        ingresses:
          enabled: true
        nodes:
          enabled: true
          syncAllNodes: true
      syncer:
        replicas: 2
      etcd:
        replicas: 2
      api:
        replicas: 2
      controller:
        replicas: 2
      ingress:
        enabled: true
  kubernetesVersion: 1.27.3