apiVersion: v1
kind: Namespace
metadata:
 name: my-cluster-k3s
---

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster-k3s
  namespace: my-cluster-k3s
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: my-cluster-k3s
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: my-cluster-k3s
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: my-cluster-k3s
  namespace: my-cluster-k3s
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
     # by default install k3s distribution
      name: null
      repo: null
      version: null
    values: |-
      service:
        type: LoadBalancer
      sync:
        persistentvolumeclaims:
          enabled: true
        ingresses:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        host: my-cluster-k3s.tactile.int
#  kubernetesVersion: 1.27.3