apiVersion: v1
kind: Namespace
metadata:
 name: my-cluster-k8s

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster-k8s
  namespace: my-cluster-k8s
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: my-cluster-k8s
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: my-cluster-k8s
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: my-cluster-k8s
  namespace: my-cluster-k8s
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: vcluster-k8s
      repo: null
      version: null
    values: |-
      service:
        type: LoadBalancer
      sync:
        persistentvolumeclaims:
          enabled: true
        ingresses:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        host: my-cluster-k8s.tactile.int
#  kubernetesVersion: v1.25.0